version: "3.1"

services:
  api:
    env_file: 
      - .env
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_APP_USER}:${POSTGRES_APP_PASSWORD}@${DATABASE_HOST}:5432/${POSTGRES_APP_DB}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: ${POSTGRES_APP_USER}
    depends_on:
      - database

  database:
    env_file: 
      - .env
    build: postgis
    # volumes:
    #   - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: 
        - CMD-SHELL
        - pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
  
# volumes:
#   database:
    